// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/hosea3000/work2api/internal/bootstrap"
	"github.com/hosea3000/work2api/internal/config"
	"github.com/hosea3000/work2api/internal/handler"
	"github.com/hosea3000/work2api/internal/job"
	"github.com/hosea3000/work2api/internal/repository"
	"github.com/hosea3000/work2api/internal/router"
	"github.com/hosea3000/work2api/internal/server"
	"github.com/hosea3000/work2api/internal/service"
	"github.com/hosea3000/work2api/pkg/app"
	"github.com/hosea3000/work2api/pkg/jwt"
	"github.com/hosea3000/work2api/pkg/log"
	"github.com/hosea3000/work2api/pkg/server/http"
	"github.com/hosea3000/work2api/pkg/sid"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	gatewayRepository := repository.NewGatewayRepository(repositoryRepository)
	sessionService := service.NewSessionService(gatewayRepository)
	authHandler := handler.NewAuthHandler(handlerHandler, sessionService)
	apiKeyService := service.NewAPIKeyService(gatewayRepository)
	apiKeyHandler := handler.NewAPIKeyHandler(handlerHandler, apiKeyService)
	codeBuddyCredentialRepository := repository.NewCodeBuddyCredentialRepository(repositoryRepository)
	codeBuddyConfig, err := config.LoadCodeBuddyConfig(viperViper)
	if err != nil {
		return nil, nil, err
	}
	credentialPool := service.NewCredentialPool(codeBuddyConfig)
	poolStateRepository := repository.NewPoolStateRepository(repositoryRepository)
	client := bootstrap.NewCodeBuddyClient(codeBuddyConfig)
	codeBuddyCredentialService := service.NewCodeBuddyCredentialService(codeBuddyCredentialRepository, credentialPool, poolStateRepository, codeBuddyConfig, client)
	codeBuddyCheckinService := service.NewCodeBuddyCheckinService(codeBuddyCredentialRepository, codeBuddyCredentialService, client, codeBuddyConfig)
	modelsService := bootstrap.NewModelsServiceFromConfig(codeBuddyConfig, client, codeBuddyCredentialService)
	codeBuddyCredentialHandler := handler.NewCodeBuddyCredentialHandler(handlerHandler, codeBuddyCredentialService, codeBuddyCheckinService, modelsService)
	traeCredentialRepository := repository.NewTraeCredentialRepository(repositoryRepository)
	traeCredentialPool := service.NewTraeCredentialPool()
	traeClient := bootstrap.NewTraeClient()
	traeCredentialService := service.NewTraeCredentialService(traeCredentialRepository, traeCredentialPool, poolStateRepository, traeClient)
	traeCheckinService := service.NewTraeCheckinService(traeCredentialRepository, traeCredentialService, traeClient, codeBuddyConfig)
	traeModelsService := bootstrap.NewTraeModelsServiceFromConfig(codeBuddyConfig, traeClient, traeCredentialService)
	traeCredentialHandler := handler.NewTraeCredentialHandler(handlerHandler, traeCredentialService, traeCheckinService, traeModelsService)
	requestPolicies := bootstrap.NewRequestPolicies(codeBuddyConfig)
	chatExecutor := service.NewChatExecutor(codeBuddyCredentialService, client, requestPolicies)
	openAIHandler := handler.NewOpenAIHandler(handlerHandler, chatExecutor, modelsService)
	adminStubHandler := handler.NewAdminStubHandler(handlerHandler)
	authStateStore := service.NewAuthStateStore()
	oAuthService := service.NewOAuthService(client, codeBuddyCredentialService, modelsService, authStateStore)
	codeBuddyAuthHandler := handler.NewCodeBuddyAuthHandler(handlerHandler, oAuthService)
	traeLoginService := service.NewTraeLoginService(traeCredentialRepository, traeClient, codeBuddyConfig)
	traeAuthHandler := handler.NewTraeAuthHandler(handlerHandler, traeLoginService)
	traeChatExecutor := service.NewTraeChatExecutor(traeCredentialService, traeClient)
	traeChatHandler := handler.NewTraeChatHandler(handlerHandler, traeChatExecutor, traeModelsService)
	routerDeps := router.RouterDeps{
		Logger:                     logger,
		Config:                     viperViper,
		JWT:                        jwtJWT,
		UserHandler:                userHandler,
		AuthHandler:                authHandler,
		APIKeyHandler:              apiKeyHandler,
		CodeBuddyCredentialHandler: codeBuddyCredentialHandler,
		TraeCredentialHandler:      traeCredentialHandler,
		OpenAIHandler:              openAIHandler,
		AdminStubHandler:           adminStubHandler,
		CodeBuddyAuthHandler:       codeBuddyAuthHandler,
		TraeAuthHandler:            traeAuthHandler,
		TraeChatHandler:            traeChatHandler,
		SessionService:             sessionService,
		APIKeyService:              apiKeyService,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	checkinJob := job.NewCheckinJob(codeBuddyCheckinService, traeCheckinService, codeBuddyConfig)
	tokenRefreshService := service.NewTokenRefreshService(codeBuddyCredentialService, client)
	traeTokenRefreshService := service.NewTraeTokenRefreshService(traeCredentialService, traeClient)
	checkinJobServer := server.NewCheckinJobServer(logger, checkinJob, codeBuddyConfig, gatewayRepository, sessionService, codeBuddyCredentialService, traeCredentialService, tokenRefreshService, traeTokenRefreshService)
	traeCallbackServer := server.NewTraeCallbackServerFromDeps(routerDeps, traeAuthHandler)
	appApp := newApp(httpServer, jobServer, checkinJobServer, traeCallbackServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewGatewayRepository, repository.NewCodeBuddyCredentialRepository, repository.NewTraeCredentialRepository, repository.NewPoolStateRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, config.LoadCodeBuddyConfig, bootstrap.NewCodeBuddyClient, bootstrap.NewRequestPolicies, bootstrap.NewModelsServiceFromConfig, service.NewCredentialPool, service.NewTraeCredentialPool, service.NewCodeBuddyCredentialService, service.NewTraeCredentialService, service.NewCodeBuddyCheckinService, service.NewTraeCheckinService, service.NewAPIKeyService, service.NewSessionService, service.NewChatExecutor, service.NewTraeChatExecutor, bootstrap.NewTraeModelsServiceFromConfig)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAuthHandler, handler.NewAPIKeyHandler, handler.NewCodeBuddyCredentialHandler, handler.NewTraeCredentialHandler, handler.NewOpenAIHandler, handler.NewAdminStubHandler, handler.NewCodeBuddyAuthHandler, handler.NewTraeAuthHandler, handler.NewTraeChatHandler, service.NewAuthStateStore, service.NewOAuthService, service.NewTokenRefreshService, service.NewTraeTokenRefreshService, service.NewTraeLoginService, bootstrap.NewTraeClient)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob, job.NewCheckinJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer, server.NewCheckinJobServer, server.NewTraeCallbackServerFromDeps)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,
	checkinServer *server.CheckinJobServer,
	traeCallbackServer *server.TraeCallbackServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer, checkinServer, traeCallbackServer), app.WithName("work2api"))
}
